# Generated by Django 5.1.4 on 2025-01-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('type', models.IntegerField()),
                ('order_no', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=250)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pub.parameters')),
            ],
            options={
                'verbose_name': 'پارامترهای عمومی',
                'verbose_name_plural': 'پارامترهای عمومی',
            },
        ),
    ]
